 name: dotnet-sonarscanner
 
 on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  
 jobs:
  run:
   runs-on: windows-latest
   steps:
     - name: go
       uses: Secbyte/dotnet-sonarscanner@v2.3
       with:
         buildCommand: dotnet build
         testCommand: dotnet test
         projectKey: Ashimaru_karaoke
         projectName: karaoke
         sonarOrganisation: ashimaru
       env:
         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}